# Nom pour le workflow
name: premier workflow

# on précise quel est le déclencheur de notre workflow
on: 
  - workflow_dispatch
  - push

# on précise les actions à réaliser lors du déclenchement de ce workflow
jobs:
  # Définition de la premiere action à réaliser
  premier-job:
    name: premier job
    # On précise le système d'exploitation
    runs-on: ubuntu-latest
    # On écrit ici les étapes pour notre action
    steps:
      # On donne un nom à notre étape et une commande à effectuer
      - name: Dit bonjour
        run: echo "Hello world !" 
      - name: Dit au revoir
        run: echo "Goodbye"
  

  second-job:
    name: Mon second job
    runs-on: ubuntu-latest
    steps:
      - name: Mon étape
        run: echo "Je suis un second job"